// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwNvmA9lA8P_rCRcyoYJxE0xGaCNYT-qo',
    appId: '1:938883769605:web:11e2141b21ef9aae57436c',
    messagingSenderId: '938883769605',
    projectId: 'learning-6a61e',
    authDomain: 'learning-6a61e.firebaseapp.com',
    storageBucket: 'learning-6a61e.firebasestorage.app',
    measurementId: 'G-HVXSHJJGZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc2zrRtz_OqDt150OL0TM1kCNguaWHifo',
    appId: '1:938883769605:android:21ac6589712b90ef57436c',
    messagingSenderId: '938883769605',
    projectId: 'learning-6a61e',
    storageBucket: 'learning-6a61e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZISPEM5eiQyRYWSDrsAt9ZO8zxpHaCwk',
    appId: '1:938883769605:ios:86ac0dcfbf74182657436c',
    messagingSenderId: '938883769605',
    projectId: 'learning-6a61e',
    storageBucket: 'learning-6a61e.firebasestorage.app',
    iosBundleId: 'com.example.learning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZISPEM5eiQyRYWSDrsAt9ZO8zxpHaCwk',
    appId: '1:938883769605:ios:86ac0dcfbf74182657436c',
    messagingSenderId: '938883769605',
    projectId: 'learning-6a61e',
    storageBucket: 'learning-6a61e.firebasestorage.app',
    iosBundleId: 'com.example.learning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwNvmA9lA8P_rCRcyoYJxE0xGaCNYT-qo',
    appId: '1:938883769605:web:69a61c34a1b46d5b57436c',
    messagingSenderId: '938883769605',
    projectId: 'learning-6a61e',
    authDomain: 'learning-6a61e.firebaseapp.com',
    storageBucket: 'learning-6a61e.firebasestorage.app',
    measurementId: 'G-R845CD1P0H',
  );
}
